# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 310fbe50a4908f1c87dcdc55c558cb5fbf9571b81d3c32ac0537b7baee82dceae7cb402b9d41930bb9269d71ab4883e25e9c4f5961f27c3d348e8fcd6068bc2c

test:
  secret_key_base: 96f062afd44398a3bf1c937469b7fd3d7bb922678c50853bd8411515a07a9b9e5da83bf4ce712f1227855fc0f10e48fd765fdfc3fff6c8cad57adf9a181f90fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
